Repository SubnauticaNitrox/Nitrox, pull requests merged in 2024-02, with the labels that each got.

#2113 Sync spawning commands
  Nitrox.Test/Patcher/Patches/Dynamic/SpawnConsoleCommand_OnConsoleCommand_PatchTest.cs
  Nitrox.Test/Patcher/Patches/Dynamic/SubConsoleCommand_OnConsoleCommand_sub_PatchTest.cs
  NitroxClient/GameLogic/MobileVehicleBay.cs
  NitroxClient/GameLogic/NitroxConsole.cs
  NitroxClient/GameLogic/Vehicles.cs
  NitroxPatcher/Patches/Dynamic/SpawnConsoleCommand_OnConsoleCommand_Patch.cs
  NitroxPatcher/Patches/Dynamic/SpawnConsoleCommand_SpawnAsync_Patch.cs
  NitroxPatcher/Patches/Dynamic/SubConsoleCommand_OnConsoleCommand_sub_Patch.cs
Labels: Type: bug, Area: vehicles

#2117 NRE fixes
  NitroxClient/Communication/NetworkingLayer/LiteNetLib/LiteNetLibClient.cs
  NitroxClient/GameLogic/LocalPlayer.cs
  NitroxPatcher/Patches/Persistent/GameAnalytics_Patch.cs
Labels: Type: bug, Area: netcode

#2121 Game finders overhaul
  .editorconfig
  Nitrox.Test/Model/ExtensionsTests.cs
  Nitrox.Test/Server/Serialization/WorldPersistenceTest.cs
  NitroxLauncher/Assets/Images/store-icons/pirated-2x.png
  NitroxLauncher/LauncherLogic.cs
  NitroxLauncher/MainWindow.xaml.cs
  NitroxLauncher/Models/Converters/PlatformToIconConverter.cs
  NitroxLauncher/Pages/LaunchGamePage.xaml.cs
  NitroxLauncher/Pages/OptionPage.xaml.cs
  NitroxModel/Discovery/GameInstallData.cs
  NitroxModel/Discovery/GameInstallationFinder.cs
  NitroxModel/Discovery/GameInstallationHelper.cs
  NitroxModel/Discovery/IFindGameInstallation.cs
  NitroxModel/Discovery/InstallationFinders/ConfigFinder.cs
  NitroxModel/Discovery/InstallationFinders/ConfigGameFinder.cs
  NitroxModel/Discovery/InstallationFinders/Core/GameFinderResult.cs
  NitroxModel/Discovery/InstallationFinders/Core/IGameFinder.cs
  NitroxModel/Discovery/InstallationFinders/DiscordFinder.cs
  NitroxModel/Discovery/InstallationFinders/DiscordGameFinder.cs
  NitroxModel/Discovery/InstallationFinders/EnvironmentFinder.cs
  NitroxModel/Discovery/InstallationFinders/EnvironmentGameFinder.cs
  NitroxModel/Discovery/InstallationFinders/EpicGamesFinder.cs
  NitroxModel/Discovery/InstallationFinders/EpicGamesInstallationFinder.cs
  NitroxModel/Discovery/InstallationFinders/GameInCurrentDirectoryFinder.cs
  NitroxModel/Discovery/InstallationFinders/MicrosoftFinder.cs
  NitroxModel/Discovery/InstallationFinders/SteamFinder.cs
  NitroxModel/Discovery/InstallationFinders/SteamGameRegistryFinder.cs
  NitroxModel/Discovery/Models/GameInstallation.cs
  NitroxModel/Discovery/Models/GameLibraries.cs
  NitroxModel/Discovery/Models/Platform.cs
  NitroxModel/Extensions.cs
  NitroxModel/GameInfo.cs
  NitroxModel/Helper/LinqExtensions.cs
  NitroxModel/Helper/NitroxUser.cs
  NitroxModel/Platforms/Store/Discord.cs
  NitroxModel/Platforms/Store/EpicGames.cs
  NitroxModel/Platforms/Store/Interfaces/IGamePlatform.cs
  NitroxModel/Platforms/Store/MSStore.cs
  NitroxModel/Platforms/Store/Steam.cs
Labels: Area: setup
