Repository SubnauticaNitrox/Nitrox, pull requests merged in 2025-04, with the labels that each got.

#2298 Get correct ApplicationData dir on linux/wine
  NitroxModel/Helper/NitroxUser.cs
Labels: OS: Linux

#2257 Fix escape pod status on joining and repairing it
  Nitrox.Test/Server/Serialization/WorldPersistenceTest.cs
  Nitrox.sln.DotSettings
  NitroxClient/Debuggers/Drawer/DrawerManager.cs
  NitroxClient/Debuggers/Drawer/Subnautica/UWEEventDrawer.cs
  NitroxClient/GameLogic/Entities.cs
  NitroxClient/GameLogic/InitialSync/PlayerPositionInitialSyncProcessor.cs
  NitroxClient/GameLogic/Spawning/Metadata/EntityMetadataManager.cs
  NitroxClient/GameLogic/Spawning/Metadata/Extractor/EscapePodMetadataExtractor.cs
  NitroxClient/GameLogic/Spawning/Metadata/Processor/EscapePodMetadataProcessor.cs
  NitroxClient/GameLogic/Spawning/Metadata/Processor/RepairedComponentMetadataProcessor.cs
  NitroxClient/GameLogic/Spawning/WorldEntities/EscapePodWorldEntitySpawner.cs
  NitroxClient/GameLogic/Spawning/WorldEntities/WorldEntitySpawnerResolver.cs
  NitroxClient/GameLogic/Spawning/WorldEntitySpawner.cs
  NitroxModel/DataStructures/GameLogic/Entities/EscapePodWorldEntity.cs
  NitroxModel/DataStructures/GameLogic/Entities/Metadata/EntityMetadata.cs
  NitroxModel/DataStructures/GameLogic/Entities/Metadata/EscapePodMetadata.cs
  NitroxModel/DataStructures/GameLogic/Entities/Metadata/RepairedComponentMetadata.cs
  NitroxPatcher/Patches/Dynamic/EscapePod_Awake_Patch.cs
  NitroxPatcher/Patches/Dynamic/EscapePod_OnRepair_Patch.cs
  NitroxPatcher/Patches/Dynamic/Radio_OnRepair_Patch.cs
  NitroxPatcher/Patches/Dynamic/uGUI_SceneIntro_HandleInput_Patch.cs
  NitroxPatcher/Patches/Dynamic/uGUI_SceneIntro_IntroSequence_Patch.cs
  NitroxPatcher/Patches/Persistent/MainGameController_ShouldPlayIntro_Patch.cs
  NitroxServer/Communication/Packets/Processors/PlayerJoiningMultiplayerSessionProcessor.cs
  NitroxServer/GameLogic/EscapePodManager.cs
Labels: Area: persistence

#2290 Fix SeaTreader_SetNextPathPoint not emitting metadata changes
  NitroxPatcher/Patches/Dynamic/SeaTreader_SetNextPathPoint_Patch.cs
Labels: Area: AI
