Repository SubnauticaNitrox/Nitrox, pull requests merged in 2025-02, with the labels that each got.

#2111 Modify teleport to move vehicle
  NitroxClient/Communication/Packets/Processors/PlayerTeleportedProcessor.cs
  NitroxPatcher/Patches/Dynamic/GotoConsoleCommand_GotoPosition_Patch.cs
  NitroxPatcher/Patches/Dynamic/Player_WarpForward_Patch.cs
Labels: Area: vehicles, Type: enhancement

#2254 Fix fake constructables being moved to GlobalRoot
  NitroxClient/GameLogic/Spawning/Bases/ModuleEntitySpawner.cs
  NitroxPatcher/Patches/Dynamic/Builder_TryPlace_Patch.cs
  NitroxPatcher/Patches/Dynamic/LargeWorldEntity_Awake_Patch.cs
Labels: Area: spawning

#2132 Water Park experience improvements
  Nitrox.Test/Patcher/Patches/PatchesTranspilerTest.cs
  Nitrox.Test/Server/Serialization/WorldPersistenceTest.cs
  NitroxClient/Communication/Packets/Processors/EntityTransformUpdatesProcessor.cs
  NitroxClient/Debuggers/Drawer/Nitrox/NitroxEntityDrawer.cs
  NitroxClient/GameLogic/InitialSync/PlayerPositionInitialSyncProcessor.cs
  NitroxClient/GameLogic/Items.cs
  NitroxClient/GameLogic/LiveMixinManager.cs
  NitroxClient/GameLogic/Spawning/Metadata/Extractor/EggMetadataExtractor.cs
  NitroxClient/GameLogic/Spawning/Metadata/Processor/EggMetadataProcessor.cs
  NitroxClient/GameLogic/Spawning/Metadata/Processor/WaterParkCreatureMetadataProcessor.cs
  NitroxClient/GameLogic/Spawning/WorldEntities/DefaultWorldEntitySpawner.cs
  NitroxClient/GameLogic/Spawning/WorldEntities/GlobalRootEntitySpawner.cs
  NitroxModel/DataStructures/GameLogic/Entities/Metadata/EggMetadata.cs
  NitroxModel/DataStructures/GameLogic/Entities/Metadata/EntityMetadata.cs
  NitroxPatcher/Patches/Dynamic/CreatureEgg_Hatch_Patch.cs
  NitroxPatcher/Patches/Dynamic/WaterParkCreature_BornAsync_Patch.cs
  NitroxPatcher/Patches/Dynamic/WaterParkCreature_ManagedUpdate_Patch.cs
  NitroxPatcher/Patches/Dynamic/WaterParkCreature_ResetBreedTime_Patch.cs
  NitroxServer/Communication/Packets/Processors/EntityTransformUpdatesProcessor.cs
  NitroxServer/Communication/Packets/Processors/UpdateBaseProcessor.cs
  NitroxServer/GameLogic/Entities/WorldEntityManager.cs
Labels: Area: bases
